---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart ssh socket
  ansible.builtin.systemd:
    name: ssh.socket
    state: restarted

- name: Reload ssh
  ansible.builtin.systemd:
    name: ssh
    state: reloaded
