---
docker_users: []
# docker_users:
#   - user

# Docker packages to install
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Apt keyring path
docker_apt_keyring: /etc/apt/keyrings/docker.asc
