---
- name: Create node-exporter system user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    system: true
    shell: /sbin/nologin
    create_home: false

- name: Check installed node_exporter version
  ansible.builtin.command: /usr/local/bin/node_exporter --version
  register: node_exporter_installed_version
  changed_when: false
  failed_when: false

- name: Download node_exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ exporter_arch }}.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    mode: "0644"
  when: >
    node_exporter_installed_version.rc != 0 or
    node_exporter_version not in node_exporter_installed_version.stdout

- name: Extract node_exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: /tmp
    remote_src: true
  when: >
    node_exporter_installed_version.rc != 0 or
    node_exporter_version not in node_exporter_installed_version.stdout

- name: Install node_exporter binary
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ exporter_arch }}/node_exporter"
    dest: "{{ exporter_bin_dir }}/node_exporter"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  notify: Restart node-exporter
  when: >
    node_exporter_installed_version.rc != 0 or
    node_exporter_version not in node_exporter_installed_version.stdout

- name: Deploy node_exporter systemd service
  ansible.builtin.template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart node-exporter

- name: Enable and start node-exporter
  ansible.builtin.systemd:
    name: node-exporter
    enabled: true
    state: started
    daemon_reload: true

- name: Allow node_exporter port in UFW
  community.general.ufw:
    rule: allow
    port: "{{ node_exporter_port }}"
    proto: tcp
    comment: "Prometheus node_exporter"
  when: ansible_facts.services['ufw.service'] is defined
  ignore_errors: true
