---
ssh_port: 22022
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_pubkey_authentication: "yes"
ssh_x11_forwarding: "no"
ssh_allow_agent_forwarding: "no"
ssh_allow_tcp_forwarding: "no"
ssh_max_auth_tries: 3
ssh_login_grace_time: 30
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
