---
ssh_port: 22022
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_pubkey_authentication: "yes"
ssh_x11_forwarding: "no"
ssh_allow_agent_forwarding: "no"
ssh_allow_tcp_forwarding: "no"
ssh_max_auth_tries: 2
ssh_max_sessions: 2
ssh_login_grace_time: 30
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 0
ssh_log_level: "VERBOSE"

# Modern crypto â€” Mozilla OpenSSH guidelines (6.7+)
# https://infosec.mozilla.org/guidelines/openssh#modern-openssh-67
ssh_kex_algorithms: "curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
ssh_ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
ssh_macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
