---
node_exporter_version: "1.8.2"
node_exporter_port: 9100
node_exporter_user: node-exporter
node_exporter_extra_args: >-
  --collector.systemd
  --collector.processes
  --collector.filesystem.mount-points-exclude='^/(sys|proc|dev|run|snap)($|/)'
