---
postgres_exporter_version: "0.15.0"
postgres_exporter_port: 9187
postgres_exporter_user: postgres-exporter
postgres_exporter_dsn: "postgresql://exporter:secret@localhost/postgres?sslmode=disable"
postgres_exporter_custom_queries: true
postgres_exporter_extra_args: ""
